### ISSUE TITLE
clang_type_inspector#inspect_type_at() mangles the terminal

### ISSUE THREAD

**Issue by vmiklos** [libclang-vim/clang-type-inspector.vim#1]
Hi,

I've put the following in my vimrc:

```
let g:clang_type_inspector#automatic_inspection = 0
map <C-i> :echo clang_type_inspector#inspect_type_at(line('.'), col('.'), {})<CR>
```

If I run gvim on a c++ file, navigate to an auto that is supposed to be something like std::string, then I beautifully get:

```
std::basic_string<char>
```

on Ctrl-I. Great.

However, I usually use vim on the console, and if I do so, Ctrl-I mangles the terminal for some reason. The output is like:

```
std::basic_string<char>6,7Allspect_type_at(line('.'), col('.'), {})
```

and the best I can do is to :q from vim, run `reset` in the shell, and then I get back to a normal state.

I'm not sure who sets the terminal, if it's libclang itself, or your vim wrapper or this vim plugin itself.

Thanks,

Miklos

**Comment by vmiklos** [comment]
https://github.com/vmiklos/libclang-vim/commit/87dbe4d4444b5d08470d8c354111cc9ff6389e41 is a workaround for this problem, should I send a PR or there is a better solution?

**Comment by rhysd** [comment]
I think the output comes from binary which is loaded dynamically and it breaks Vim's screen.
In libclang-vim,  I don't output anything (only returning string to Vim).  So I think it is output by libclang.

> should I send a PR or there is a better solution?

PR is helpful :smile:
